export type Role = 'Admin' | 'Project Manager' | 'Developer' | 'Designer' | 'QA Tester' | 'Marketer';

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: Role;
  avatar: string;
  joinedDate: string;
  salaryAmount: number; // monthly pay
  paymentsPaid: { month: string; amount: number; paidDate: string; txId: string }[];
  phone?: string;
  skills?: string[];
}

export type TaskStatus = 'Pending' | 'In Progress' | 'Submitted' | 'Completed';
export type TaskPriority = 'Low' | 'Medium' | 'High';

export interface Task {
  id: string;
  title: string;
  description: string;
  assignedToId: string;
  dueDate: string;
  priority: TaskPriority;
  status: TaskStatus;
  submissionNote?: string;
  createdAt: string;
  attachments?: { name: string; url: string; type: string }[];
}

export interface Client {
  id: string;
  name: string;
  companyName: string;
  email: string;
  phone: string;
  projectName: string;
  totalBudget: number;
  paidAmount: number;
  dueAmount: number;
  status: 'Active' | 'Completed' | 'Pending' | 'On Hold';
  notes?: string;
}

export interface Service {
  id: string;
  name: string;
  description: string;
  category: 'Development' | 'Design' | 'Marketing' | 'Support' | 'Consulting';
  basePrice: number;
  duration: string;
}

export interface Meeting {
  id: string;
  title: string;
  dateTime: string;
  duration: number; // minutes
  agenda: string;
  participants: string[]; // TeamMember IDs
  summary?: string;
  isCompleted: boolean;
  notes?: string;
}

export interface Transaction {
  id: string;
  clientId?: string;
  type: 'Income' | 'Expense';
  category: string;
  amount: number;
  date: string;
  description: string;
  bankAccountId?: string; // Added to log which account was used
  paymentMethod?: string; // Added (Cash, bKash, Bank Transfer, etc.)
}

export interface BankAccount {
  id: string;
  accountName: string;
  accountType: 'Bank' | 'Mobile Banking' | 'Cash';
  accountNumber?: string;
  branchName?: string;
  balance: number;
}

export interface AppSettings {
  agencyName: string;
  agencyLogoInitials: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
  currency: 'USD' | 'BDT';
  paymentDetails: string;
  showCustomLoginSim: boolean;
  expenseCategories?: string[];
  incomeCategories?: string[];
  filePinCode?: string; // 4-digit PIN to access File Manager
}

export interface CompanyFile {
  id: string;
  name: string;
  category: string; // 'Software Systems' | 'Websites' | 'Templates' | 'Assets' | 'Source Code' | 'Documentation' | 'Other'
  uploadedBy: string;
  uploadedAt: string;
  size: string;
  url: string;
  type: string; // e.g., 'zip', 'pdf', 'png', 'jpg', 'javascript'
  description?: string;
  isLocked?: boolean;
}

export interface EmployeeReport {
  id: string;
  employeeId: string;
  employeeName: string;
  title: string;
  content: string;
  date: string;
  type: 'Daily' | 'Weekly' | 'Monthly' | 'Expense Request';
  status: 'Pending' | 'Approved' | 'Reviewed';
  adminFeedback?: string;
  attachments?: { name: string; url: string; type: string }[];
}

export interface ChatMessage {
  id: string;
  senderId: string; // 'admin', or team ID (e.g. 'tm3'), or client ID (e.g. 'cl1')
  senderName: string;
  senderRole: 'Admin' | 'Employee' | 'Client';
  receiverId: string; // 'admin', 'all', or specific client/employee ID
  message: string;
  timestamp: string;
  attachments?: { name: string; url: string; type: string }[];
}

export interface Agreement {
  id: string;
  companyName: string;
  employeeId: string;
  employeeName: string;
  employeeRole: string;
  projectName: string;
  projectDescription: string;
  agreementText: string; // Markdown / Text generated by AI
  legalTermsSummary?: string; // The terms provided (e.g., "Must deliver within 30 days...")
  createdAt: string;
  status: 'Draft' | 'Sent' | 'Signed' | 'Terminated';
  employeeSignature?: string; // e.g. signed name or "Signed digitally on [date]"
  adminSignature?: string; // e.g. signed name or "Signed by Zakir Hasan on [date]"
  signedAt?: string;
}



